name: Deployment for vue application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v5

      - name: Install packages
        run: npm i

      - name: Build project
        run: npm run build

      - name: Upload to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: dist


